version: '3'
services:
  app:
    image: eyeverify
    volumes:
      - .:/backend
    depends_on:
      - db  
      - redis
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=eyeverify_db
      - DB_USER=postgres
      - DB_PASS=postgres
  
  db:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eyeverify_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  pg-admin:
    image: dpage/pgadmin4:7.7
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - db
volumes:
  data: 
